"""add column to applications

Revision ID: e4df796c9460
Revises: ee994bedb29b
Create Date: 2026-05-22 20:19:53.077155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4df796c9460'
down_revision: Union[str, Sequence[str], None] = 'ee994bedb29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'company_name')
    # ### end Alembic commands ###
